// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  engine: 'classic',
  datasource: {
    // Validated as required by env.validation.ts at app boot; the CLI
    // itself just needs a non-undefined value to satisfy its types here.
    url: process.env.DATABASE_URL ?? '',
  },
});
